### PR TITLE
Initial Commit to feedback branch.

### PR DESCRIPTION
**Pull request by farnaz91**
Hi, @farnaz91 I have used global constant here and wasnt sure how it works

### CODE REVIEW

**Comment by kissehandrew** [comment]
Hi Farnaz,

I'm having a hard time linking my pycharm on here. wanted you to check this codes and see if im making any progress 

def readMusicFromFile(filename):
   list_of_file_content = []
   try:
       openfile = open(filename,"r")
       for eachline in openfile:
           list_of_file_content.append(eachline.replace("\n",""))
       openfile.close()
   except FileNotFoundError:
       pass
   return list_of_file_content

**Comment by farnaz91** [comment]
> Hi Farnaz,
> 
> I'm having a hard time linking my pycharm on here. wanted you to check this codes and see if im making any progress
> 
> def readMusicFromFile(filename):
> list_of_file_content = []
> try:
> openfile = open(filename,"r")
> for eachline in openfile:
> list_of_file_content.append(eachline.replace("\n",""))
> openfile.close()
> except FileNotFoundError:
> pass
> return list_of_file_content

Hi

**Comment by farnaz91** [comment]
> Hi Farnaz,
> 
> I'm having a hard time linking my pycharm on here. wanted you to check this codes and see if im making any progress
> 
> def readMusicFromFile(filename):
> list_of_file_content = []
> try:
> openfile = open(filename,"r")
> for eachline in openfile:
> list_of_file_content.append(eachline.replace("\n",""))
> openfile.close()
> except FileNotFoundError:
> pass
> return list_of_file_content

HI @kissehandrew 

Coud you please send me your entire code of assignment to my email in the zip file and I will send you feedback in there.

Thanks

**Comment by kissehandrew** [comment]
Hi Farnaz,

Hope to hear from you soon

Kind regards Andrew

**Pull request closed without merging**
